/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void jump_to_application(const uint32_t app_address)
{
	typedef void (*jump_fnPtr)();

	const uint32_t resetHandler = *(__IO uint32_t *)(app_address + 4); /* Address of application's Reset Handler */
	jump_fnPtr run = (jump_fnPtr)resetHandler; /* Function pointer to jump to application's Reset Handler */

	/* Deinit peripherals here */

	__set_MSP(*((__IO uint32_t*) app_address)); /* CMSIS function - set main stack pointer */
	run(); /* Jump to application */
}

extern uint32_t _sapp1;
extern uint32_t _sapp2;

int main(void)
{

	jump_to_application((uint32_t)&_sapp1);

    /* Loop forever */
	for(;;);
}
