/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "led.h"
#include "systick.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern uint32_t _bootram;
uint32_t *bootram = &_bootram;

extern uint32_t _sflash;
extern uint32_t _isr_origin;

/* System initialization function, called before main() in startup script */
void SystemInit()
{
	/* Set vector table offset - for interrupt handlers addresses offset */
	SCB->VTOR = ((uint32_t)&_isr_origin - (uint32_t)&_sflash);
}

int main(void)
{
	user_led_init();
	SysTick_1hz_interrupt();

    /* Loop forever */
	while(1)
	{
		for(uint8_t i = 0; i < 20; i++)
		{
			led_toggle(LED2);
			for(unsigned int counter=0; counter<0xFFFFF; counter++);
		}
			bootram[0]++;
			bootram[1] = bootram[0] + 3;
			bootram[2] = bootram[1] * bootram[0];
			NVIC_SystemReset();
	}
}

void SysTick_Handler()
{
	led_toggle(LED1);
}
